name: Feature request
description: Suggest an idea for this project
title: "[Feat] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: |
        List the specific requirements that must be met for this feature to be considered complete.
      placeholder: |
        - [ ] User can do X
        - [ ] System responds with Y
        - [ ] Feature works on mobile

  - type: dropdown
    id: component-category
    attributes:
      label: Component category
      description: Which category does this feature belong to?
      options:
        - Primitives (Button, Card, etc.)
        - Layout (Header, Footer, etc.)
        - Form (Input, Select, etc.)
        - Marketing (Hero, CTA, etc.)
        - Navigation (Breadcrumbs, Tabs, etc.)
        - Data Display (Table, Badge, etc.)
        - Overlay (Modal, Tooltip, etc.)
        - System (Theme, Error, etc.)
        - Other

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Please check all that apply
      options:
        - label: This feature should be accessible (WCAG 2.1 AA)
          required: false
        - label: This feature should work with all brand themes
          required: false
        - label: This feature should be responsive
          required: false
        - label: This feature needs documentation/stories
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.
