name: CI
on:
  push: { branches: [main] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Corepack / pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.6.0 --activate
          node -v && pnpm -v

      - name: Install
        run: pnpm -w install --frozen-lockfile

      - name: Build libs & apps
        run: |
          pnpm -w run build:tokens && pnpm -w run build:ui && pnpm -w run build

      - name: Lint
        run: pnpm -w run lint

      - name: Typecheck
        run: pnpm -w run typecheck
