name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        run: corepack enable && corepack prepare pnpm@9.6.0 --activate

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm -w build

  ladle-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: ci
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        run: corepack enable && corepack prepare pnpm@9.6.0 --activate

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Ladle static
        run: pnpm build:ladle

      - name: Upload Ladle preview
        uses: actions/upload-artifact@v4
        with:
          name: ladle-preview
          path: apps/ladle/build/
          retention-days: 7
